# Generated by Django 4.2.6 on 2023-11-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('sensor_type', models.CharField(choices=[('TEMP', 'Temperature'), ('HUM', 'Humidity'), ('LIGHT', 'Light')], max_length=5)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('last_reading', models.FloatField(blank=True, null=True)),
                ('last_reading_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
